[eye_tracker]
binary_threshold_left = 70
binary_threshold_right = 70
fill_n_vetical_dark_pixels_left = 5
fill_n_vetical_dark_pixels_right = 15
fill_n_horizontal_dark_pixels_left = 0
fill_n_horizontal_dark_pixels_right = 0
masking_radius_left = 200
masking_radius_right = 200
masking_center_left = [
    150,
    0,
]
masking_center_right = [
    -50,
    -50,
]
do_ellipse_fitting = true
overlay_ellipse = true
frame_returned = "original"
